# Copyright (C) 1991-2012 Altera Corporation
# Your use of Altera Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License 
# Subscription Agreement, Altera MegaCore Function License 
# Agreement, or other applicable license agreement, including, 
# without limitation, that your use is for the sole purpose of 
# programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the 
# applicable agreement for further details.


# ***************************************************************************
# ***************************************************************************
# 
# File:		C:/Users/okey-/OneDrive/Escritorio/proximo semestre/Arquitectura de computadoras/verylog/alu_sum_res_mul/simulation/modelsim/ALU_basica_dump_all_vcd_nodes.tcl
# 
# Description:	Script for ModelSim (Verilog) VCD File Dumping
# 		This script is used to direct ModelSim (Verilog) to dump
# 		all nodes in the design to a VCD output file
# 
# Usages:	C:/Users/okey-/OneDrive/Escritorio/proximo semestre/Arquitectura de computadoras/verylog/alu_sum_res_mul/simulation/modelsim/ALU_basica_dump_all_vcd_nodes.tcl
# 
# Generated by:	Quartus II 32-bit
# 		Version 12.1 Build 177 11/07/2012 SJ Web Edition
# 
# Date:		Thu Dec 08 11:49:25 2022
# 
# Design:	ALU_basica
# 
# ***************************************************************************
# ***************************************************************************

# ----------------------------------------------------------------
#
proc add_vcd_signals { hierarchy vcd_filename } {
#
# Description:	This function directs ModelSim (Verilog) to print out the
#		appropriate VCD signals, with the hierarchy level
#		prepended to each signal name
#
# ----------------------------------------------------------------

   catch { vcd add "$hierarchy/Mux15_a0_combout" }
   catch { vcd add "$hierarchy/Mux15_a1_combout" }
   catch { vcd add "$hierarchy/F2_aE1\[0\]" }
   catch { vcd add "$hierarchy/F0_aU0_ae_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU0_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/Mux14_a2_combout" }
   catch { vcd add "$hierarchy/Mux14_a3_combout" }
   catch { vcd add "$hierarchy/F1_aU2_awire1_a0_combout" }
   catch { vcd add "$hierarchy/F0_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE2\[0\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/Mux13_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/Mux13_a1_combout" }
   catch { vcd add "$hierarchy/F2_aE0\[3\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE2\[1\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE3\[0\]" }
   catch { vcd add "$hierarchy/F0_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F0_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU1_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/F1_aU2_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/Mux12_a2_combout" }
   catch { vcd add "$hierarchy/Mux12_a3_combout" }
   catch { vcd add "$hierarchy/F2_aE3\[1\]" }
   catch { vcd add "$hierarchy/F0_aU2_ae_a1_combout" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU3_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE4\[0\]" }
   catch { vcd add "$hierarchy/F0_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU3_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/Mux11_a2_combout" }
   catch { vcd add "$hierarchy/Mux11_a3_combout" }
   catch { vcd add "$hierarchy/F2_aE4\[1\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU4_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE0\[4\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU3_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE3\[2\]" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE5\[0\]" }
   catch { vcd add "$hierarchy/F0_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU4_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/Mux10_a2_combout" }
   catch { vcd add "$hierarchy/Mux10_a3_combout" }
   catch { vcd add "$hierarchy/F2_aE5\[1\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU5_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE0\[5\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU4_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE2\[3\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU3_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE4\[2\]" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE6\[0\]" }
   catch { vcd add "$hierarchy/F0_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU5_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/Mux9_a2_combout" }
   catch { vcd add "$hierarchy/Mux9_a3_combout" }
   catch { vcd add "$hierarchy/F2_aE6\[1\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU6_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE0\[6\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU5_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE2\[4\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU4_areg1_acombout" }
   catch { vcd add "$hierarchy/F0_aU3_ae_a1_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU3_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE5\[2\]" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aE7\[0\]" }
   catch { vcd add "$hierarchy/F0_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F1_aU6_aoutBorr_acombout" }
   catch { vcd add "$hierarchy/Mux8_a2_combout" }
   catch { vcd add "$hierarchy/Mux8_a3_combout" }
   catch { vcd add "$hierarchy/F2_aE7\[1\]" }
   catch { vcd add "$hierarchy/F2_aE0\[7\]" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE1\[7\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU6_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE2\[5\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU5_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE3\[4\]" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU4_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE4\[3\]" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU3_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE6\[2\]" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU1_ad_acombout" }
   catch { vcd add "$hierarchy/Mux7_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE2\[6\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU6_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE3\[5\]" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU5_areg1_acombout" }
   catch { vcd add "$hierarchy/F0_aU4_ae_a1_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU4_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE5\[3\]" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU3_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE7\[2\]" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU1_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU2_ad_acombout" }
   catch { vcd add "$hierarchy/Mux6_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE2\[7\]" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU7_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU7_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE3\[6\]" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU6_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE4\[5\]" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU5_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE5\[4\]" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU4_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE7\[3\]" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU2_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE6\[3\]" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU3_ad_acombout" }
   catch { vcd add "$hierarchy/Mux5_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder2_aU7_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU7_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE4\[6\]" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU6_areg1_acombout" }
   catch { vcd add "$hierarchy/F0_aU5_ae_a1_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU5_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE7\[4\]" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU3_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE6\[4\]" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU4_ad_acombout" }
   catch { vcd add "$hierarchy/Mux4_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder3_aU7_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU7_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE5\[6\]" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU6_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE7\[5\]" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU4_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE6\[5\]" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU5_ad_acombout" }
   catch { vcd add "$hierarchy/Mux3_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder4_aU7_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU7_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU5_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aE7\[6\]" }
   catch { vcd add "$hierarchy/F0_aU6_ae_a1_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU6_ad_acombout" }
   catch { vcd add "$hierarchy/Mux2_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU6_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder5_aU7_ae_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU7_ad_a0_combout" }
   catch { vcd add "$hierarchy/Mux1_a0_combout" }
   catch { vcd add "$hierarchy/F2_aAdder6_aU7_ae_a0_combout" }
   catch { vcd add "$hierarchy/Mux0_a0_combout" }
   catch { vcd add "$hierarchy/Mux16_a0_combout" }
   catch { vcd add "$hierarchy/Mux16_a1_combout" }
   catch { vcd add "$hierarchy/Mux16_a2_combout" }
   catch { vcd add "$hierarchy/Mux14_a4_combout" }
   catch { vcd add "$hierarchy/Mux12_a4_combout" }
   catch { vcd add "$hierarchy/Mux11_a4_combout" }
   catch { vcd add "$hierarchy/Mux10_a4_combout" }
   catch { vcd add "$hierarchy/Mux9_a4_combout" }
   catch { vcd add "$hierarchy/Mux8_a4_combout" }
   catch { vcd add "$hierarchy/F2_aAdder1_aU7_areg1_acombout" }
   catch { vcd add "$hierarchy/F2_aE0_a1_a_a0_combout" }
   catch { vcd add "$hierarchy/F0_aU1_ae_a1_combout" }
   catch { vcd add "$hierarchy/F2_aE0_a2_a_a1_combout" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU1_ae_a3_combout" }
   catch { vcd add "$hierarchy/F2_aAdder0_aU1_ae_a9_combout" }
   catch { vcd add "$hierarchy/ALU_out_a0_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a1_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a2_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a3_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a4_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a5_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a6_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a7_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a8_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a9_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a10_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a11_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a12_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a13_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a14_a_aoutput_o" }
   catch { vcd add "$hierarchy/ALU_out_a15_a_aoutput_o" }
   catch { vcd add "$hierarchy/flag_aoutput_o" }
   catch { vcd add "$hierarchy/A_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/sel_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/sel_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/c_ainput_o" }
   catch { vcd add "$hierarchy/B_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a4_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a4_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a5_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a5_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a6_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a6_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a7_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a7_a_ainput_o" }
}

# ----------------------------------------------------------------
#
proc main { argv } {
#
# Description:	Main entry point to script.  Iterate over all
#		hierarchy levels specified, and direct ModelSim (Verilog)
#		to print the relevant signals under each level
#
# ----------------------------------------------------------------

   set vcd_filename "ALU_basica.vcd"
   set hierarchy "ALu.vcd"

   vcd file "$vcd_filename"
   vcd on

   add_vcd_signals $hierarchy $vcd_filename
}

main $argv
